services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../vela.env
    volumes:
      - ..:/workspaces/vela:cached
    command: sleep infinity
    ports:
      - "3000:3000"
      - "5050:5050"